# Generated by Django 3.0.5 on 2020-04-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trialTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trialtable_title', models.CharField(max_length=200)),
                ('trialtable_content', models.TextField()),
                ('trialtable_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
