# Generated by Django 3.0.5 on 2020-04-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeachTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beach_id', models.PositiveIntegerField()),
                ('beach_name', models.TextField()),
                ('beach_latitude', models.FloatField()),
                ('beach_longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HospitalTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.PositiveIntegerField()),
                ('hospital_name', models.TextField()),
                ('hospital_address', models.TextField()),
                ('hospital_wt', models.FloatField()),
                ('hospital_latitude', models.FloatField()),
                ('hospital_longitude', models.FloatField()),
            ],
        ),
    ]
